### ISSUE TITLE
Renaming of these connectors is necessary for them to work with the new connector symbols

### ISSUE THREAD

**Issue by poeschlr** [KiCad/Connectors_Mini-Universal.pretty#2]
These connectors will not work with the new connector symbols added by https://github.com/KiCad/kicad-library/pull/1561

They should be renamed to fit whatever naming scheme we decide to use in https://github.com/KiCad/kicad-library/issues/1447

I think these connectors are a series of connectors made by TEConnectivity:
http://www.mouser.com/pdfdocs/TEConnectivityMiniUniversalMATENLOKQuickReferenceGuide.PDF (page 3)
This would mean they should be moved to https://github.com/KiCad/Connectors_TE-Connectivity.pretty
Which would mean this repo should be marked as deprecated.

**Comment by SchrodingersGat** [comment]
@poeschlr closing this, these issues should be addressed as we move to the new repo. Thanks :)
